name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 4: Get numeric timestamp
      - name: Get numeric timestamp
        id: ts
        run: echo "timestamp=$(date +%s)" >> $GITHUB_ENV

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            aghanim10/agh-ui:${{ env.timestamp }}
            aghanim10/agh-ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Post webhook to update vps server
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK }}
